# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: deploy_instance

trigger:
  - feature/powershell-deploy

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - publish: $(Build.SourcesDirectory)/Solutions
      artifact: marain_instance


- stage: deploy_to_jd
  variables:
    Endjin_AzureLocation: uksouth
    Endjin_SubscriptionId: 13821a69-41a3-43ab-9577-1519963ea474
    Endjin_AzureServiceConnection: marjd-ado-spn
    Endjin_EnvironmentSuffix: jd
    Marain_Instance_Type: Development
    Marain_ResourcePrefix: marain
  displayName: Deploy to 'jd' environment stage
  jobs:
  - deployment: deploy_jd
    displayName: Deploy to 'jd' environment  
    pool:
      vmImage: 'ubuntu-latest'
    environment: marain_jd
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: marain_instance

          - task: AzurePowerShell@5
            displayName: 'Environment debug'
            inputs:
              azureSubscription: '$(Endjin_AzureServiceConnection)'
              ScriptType: InlineScript
              Inline: |
                Write-Host "*** Environment info:"
                gci env:\ | ft -AutoSize | Out-String | Write-Host
                Write-Host "*** Vars info:"
                gci variable:\ | ft -AutoSize | Out-String | Write-Host
                Write-Host "*** Module info:"
                Get-Module -ListAvailable | Select Name,Version,Path
              preferredAzurePowerShellVersion: '2.6.0'
              pwsh: true

          - template: azurepipeline-templates/deploy-marain-instance.yml
            parameters:
              azureServiceConnection: $(Endjin_AzureServiceConnection)
              azureSubscriptionId: $(Endjin_SubscriptionId)
              azureTenantId: $(Endjin_AadTenantId)
              azureLocation: $(Endjin_AzureLocation)
              marainEnvironmentSuffix: $(Endjin_EnvironmentSuffix)
              marainInstanceType: $(Marain_Instance_Type)
              marainResourcePrefix: $(Marain_ResourcePrefix)
              workingDirectory: $(Pipeline.Workspace)/marain_instance/Marain.Instance.Deployment


- stage: deploy_to_endjin_dev
  variables:
    Endjin_AzureLocation: northeurope
    Endjin_SubscriptionId: 98333d29-7302-4f93-a51d-70c49ca7e180
    Endjin_AzureServiceConnection: maraindev-endjindev-ado-spn
    Endjin_EnvironmentSuffix: dev
    Marain_Instance_Type: Development
    Marain_ResourcePrefix: mar
  displayName: Deploy to 'endjin-dev' environment stage
  jobs:
  - deployment: deploy_endjin_dev
    displayName: Deploy to 'endjin-dev' environment  
    pool:
      vmImage: 'ubuntu-latest'
    environment: marain_endjin_dev
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: marain_instance

          - template: azurepipeline-templates/deploy-marain-instance.yml
            parameters:
              azureServiceConnection: $(Endjin_AzureServiceConnection)
              azureSubscriptionId: $(Endjin_SubscriptionId)
              azureTenantId: $(Endjin_AadTenantId)
              azureLocation: $(Endjin_AzureLocation)
              marainEnvironmentSuffix: $(Endjin_EnvironmentSuffix)
              marainInstanceType: $(Marain_Instance_Type)
              marainResourcePrefix: $(Marain_ResourcePrefix)
              workingDirectory: $(Pipeline.Workspace)/marain_instance/Marain.Instance.Deployment
