# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: marain_ps_deployment

trigger:
  - feature/powershell-deploy

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - publish: $(Build.SourcesDirectory)/Solutions
      artifact: marain_instance
    
- stage: deploy_to_jd
  variables:
    Endjin_AzureLocation: uksouth
    Endjin_SubscriptionId: 13821a69-41a3-43ab-9577-1519963ea474
    Endjin_AzureServiceConnection: jamesdawson-mpn-subscription
    Endjin_EnvironmentSuffix: jd
    Marain_Aad_App_Ids: "@{marjdtenancy='f4a33e95-36b0-4354-94d3-ad29266e1e79'; marjdoperationscontrol='c7f5ff45-f37f-440a-b84d-8ea71fa79062'}"
  displayName: Deploy to 'jd' environment stage
  jobs:
  - deployment: deploy_jd
    displayName: Deploy to 'jd' environment  
    pool:
      vmImage: 'ubuntu-latest'
    environment: marain_jd
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: marain_instance
          - task: AzurePowerShell@5
            displayName: 'Environment debug'
            inputs:
              azureSubscription: '$(Endjin_AzureServiceConnection)'
              ScriptType: InlineScript
              Inline: |
                Write-Host "*** Environment info:"
                gci env:\
              preferredAzurePowerShellVersion: '2.6.0'
              pwsh: true
              workingDirectory: $(Pipeline.Workspace)/marain_instance
          # - task: AzurePowerShell@5
          #   displayName: 'Deploy Marain environment'
          #   inputs:
          #     azureSubscription: '$(Endjin_AzureServiceConnection)'
          #     ScriptType: 'FilePath'
          #     ScriptPath: './Deploy-MarainInstanceInfrastructure.ps1'
          #     ScriptArguments: >
          #       -AzureLocation $(Endjin_AzureLocation)
          #       -EnvironmentSuffix $(Endjin_EnvironmentSuffix)
          #       -AadTenantId $(Endjin_AadTenantId)
          #       -SubscriptionId $(Endjin_SubscriptionId)
          #       -InstanceManifest $(Build.SourcesDirectory)/Solutions/InstanceManifests/Development.json
          #     # -AadAppIds @{"mardevtenancy"="$(Endjin_TenancyAppId)";"mardevoperationscontrol"="$(Endjin_OperationsControlAppId)"} -DoNotUseGraph'
          #     preferredAzurePowerShellVersion: '2.6.0'
          #     pwsh: true
          #     workingDirectory: Solutions/Marain.Instance.Deployment