# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: PR checks

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: marain-github

trigger: none
pr:
- master

variables:
  Endjin_AzureLocation: northeurope
  Endjin_SubscriptionId: 98333d29-7302-4f93-a51d-70c49ca7e180
  Endjin_AzureServiceConnection: endjin-internal-development
  Endjin_EnvironmentSuffix: td
  Marain_Instance_Type: Development
  Marain_ResourcePrefix: mar


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Snapshot_Deploy_Sources
    displayName: Snapshot deployment sources for pipeline
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - publish: $(Build.SourcesDirectory)/Solutions
      artifact: marain_instance


- stage: Test_Deployment
  displayName: Test deployment stage
  jobs:
  - deployment: deploy_td
    displayName: Deploy to 'td' environment  
    pool:
      vmImage: 'ubuntu-latest'
    environment: marain_td
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: marain_instance

          - task: AzurePowerShell@5
            displayName: 'Environment debug'
            inputs:
              azureSubscription: '$(Endjin_AzureServiceConnection)'
              ScriptType: InlineScript
              Inline: |
                Write-Host "*** Environment info:"
                gci env:\ | ft -AutoSize | Out-String | Write-Host
                Write-Host "*** Vars info:"
                gci variable:\ | ft -AutoSize | Out-String | Write-Host
                Write-Host "*** Module info:"
                Get-Module -ListAvailable | Select Name,Version,Path
              # Temporarily force a downgrade of the AzurePowerShell cmdlets because (as of September 2020 and v4.6.0) a bug
              # was introduced which breaks use of securestring with ARM templates:
              # https://github.com/Azure/azure-powershell/issues/12792
              # https://github.com/Azure/azure-powershell/issues/12819
              # Once this issue is fixed, we should revert back to using the latest version of the cmdlets.
              preferredAzurePowerShellVersion: '4.4.0'
              pwsh: true

          - template: azurepipeline-templates/deploy-marain-instance.yml
            parameters:
              azureServiceConnection: $(Endjin_AzureServiceConnection)
              azureSubscriptionId: $(Endjin_SubscriptionId)
              azureTenantId: $(Endjin_AadTenantId)
              azureLocation: $(Endjin_AzureLocation)
              marainEnvironmentSuffix: $(Endjin_EnvironmentSuffix)
              marainInstanceType: $(Marain_Instance_Type)
              marainResourcePrefix: $(Marain_ResourcePrefix)
              workingDirectory: $(Pipeline.Workspace)/marain_instance/Marain.Instance.Deployment

- stage: Cleardown_Test_Deploynent
  displayName: Cleardown test deployment
  jobs:
  - job: cleardown_test_deploynent
    displayName: Cleardown test deployment
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzurePowerShell@4
      condition: and(succeeded(), eq(variables['SkipCleardown'], ''))
      displayName: 'Delete Azure resources'
      inputs:
        azureSubscription: '$(Endjin_AzureServiceConnection)'
        ScriptType: InlineScript
        Inline: |
          $prefix = "$(Marain_ResourcePrefix)"
          $suffix = "$(Endjin_EnvironmentSuffix)"
          @("workflow","operations","tenancy","instance") | % {
            $groupName = "{0}.{1}.{2}" -f $prefix, $_, $suffix
            Write-Host ("Checking resource group: {0}" -f $groupName)
            Get-AzResourceGroup $groupName -ErrorAction SilentlyContinue | Select -First 1 | Remove-AzResourceGroup -Verbose -Force
          }
          @("tenancy","operationscontrol","workfloweng","workflowmi","tenantadmin") | % {
              $appName = "{0}{1}{2}" -f $prefix, $suffix, $_
              Write-Host ("Checking AzureAD application: {0}" -f $appName)
              Get-AzADApplication -DisplayName $appName | Select -First 1 | Remove-AzADApplication -Verbose -Force
          }
        # Temporarily force a downgrade of the AzurePowerShell cmdlets because (as of September 2020 and v4.6.0) a bug
        # was introduced which breaks use of securestring with ARM templates:
        # https://github.com/Azure/azure-powershell/issues/12792
        # https://github.com/Azure/azure-powershell/issues/12819
        # Once this issue is fixed, we should revert back to using the latest version of the cmdlets.
        preferredAzurePowerShellVersion: '4.4.0'
        pwsh: true
